language: ruby
rvm:
 - 2.5.3
 - 2.7.0
before_install:
  - sudo apt-get install -y libvips-tools
services:
  - postgresql
cache:
  bundler: true
  directories:
    - /home/travis/.rvm/
addons:
  postgresql: "9.6"
  apt:
    sources:
    - sourceline: "ppa:mc3man/trusty-media"
    packages:
    - ffmpeg
gemfile:
  - gemfiles/rails_52.gemfile
  - gemfiles/rails_60.gemfile
jobs:
  exclude:
    - rvm: 2.7.0
      gemfile: gemfiles/rails_52.gemfile
